import type { Metadata } from "next";
import "@mantine/core/styles.css";
import "@mantine/notifications/styles.css";
import {
  ColorSchemeScript,
  MantineProvider,
  mantineHtmlProps,
} from "@mantine/core";
import { Notifications } from "@mantine/notifications";
import { ModalsProvider } from "@mantine/modals";
import "dayjs/locale/de";
import { DatesProvider } from "@mantine/dates";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { theme } from "@lib/theme";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" {...mantineHtmlProps}>
      <head>
        <ColorSchemeScript />
      </head>
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <MantineProvider theme={theme}>
          <Notifications />
          <DatesProvider
            settings={{
              locale: "de",
              timezone: "Europe/Berlin",
            }}
          >
            <ModalsProvider>{children}</ModalsProvider>
          </DatesProvider>
        </MantineProvider>
      </body>
    </html>
  );
}
